apiVersion: "v1"
kind: Pod
metadata:
  name: calcfrontend
  labels:
    name: calcfrontend
    app: calcfrontend
spec:
  containers:
    - name: calcfrontend
      image: hellodemodz234.azurecr.io/calcfrontend:latest
      ports:
        - containerPort: 3000
          name: http
          protocol: TCP
      env:       
        - name: "ENDPOINT"
          value: "calcbackend"                  