apiVersion: v1
kind: Service
metadata:
  name: calcfrontend
  labels:
    name: calcfrontend
    app: calcfrontend
spec:
  selector:
    name: calcfrontend 
  type: NodePort
  ports:
   - port: 80
     name: http
     targetPort: 3000
     protocol: TCP